name: maraudr_app
description: "The Maraudr mobile application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.4
  dio: ^5.4.0
  go_router: ^13.0.1
  flutter_secure_storage: ^9.0.0
  geolocator: ^11.0.0
  provider: ^6.1.2
  equatable: ^2.0.5
  mobile_scanner: ^4.0.1
  flutter_map: ^7.0.2
  lucide_icons: ^0.257.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
